@host = https://localhost:7112

POST {{host}}/api/organizations/
Content-Type: application/json

{
  "name": "  Acme  "
}

###

POST {{host}}/api/organizations/
Content-Type: application/json

{
  "name": "   "
}
