@host = http://localhost:5185

GET {{host}}/openapi/v1.json
Accept: application/json

###

GET {{host}}/api/unknown
Accept: application/problem+json

###

POST {{host}}/api/organizations/
Content-Type: application/json

{
  "name": "  Acme  "
}

###

POST {{host}}/api/organizations/
Content-Type: application/json

{
  "name": "   "
}
